<html>
<head>
</head>
<body>
    <h3> Membuat Form dengan Method POST </h3>
    <form action= "tampil.php" method="post">
        Nama : <input type="text" name="nama"><br><br>
        Email : <input type="text" name="email"><br><br>
        Jenis Kelamin :<br>
        <input type="radio" name="gender" value="female">female
        <input type="radio" name="gender" value="male">male
        <input type="radio" name="gender" value="other">other
        <br><br> 

    <h3>Operasi aritmatika dengan method POST</h3>
        a : <input type="integer" name="a"><br><br>
        b : <input type="integer" name="b"><br><br>
        <input type="submit"><br>
    </form>

</body>
</html>